export default function HeadContent() {
  return (
    <>
      <title>Next Yeti labs Starter</title>

      <meta name="description" content="Generated by create next app" />

      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
